# Generated by Django 3.0.8 on 2020-11-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Municipio'),
        ),
    ]
