# Generated by Django 3.0.8 on 2020-11-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_provincia_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincia',
            name='location',
        ),
    ]
