# Generated by Django 3.0.8 on 2020-11-25 19:50

from django.db import migrations, models
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_remove_provincia_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', places.fields.PlacesField(max_length=255)),
            ],
        ),
    ]
