# Generated by Django 3.0.8 on 2020-11-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_maplocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapLocation',
        ),
    ]
