# Generated by Django 3.0.8 on 2020-11-25 20:34

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_provincia_location_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincia',
            name='location_f',
        ),
        migrations.AddField(
            model_name='provincia',
            name='location_m',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
    ]
