# Generated by Django 3.0.8 on 2020-11-26 17:49

from django.db import migrations
import location.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20201125_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='location_m',
            field=location.models.PatchedMultiSelectField(blank=True, max_length=255, null=True),
        ),
    ]
